Spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/generic

    username: root
    password: pass
    driverClassName: org.mariadb.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    hibernate:
      ddl-auto: update
      dialect: MySQL8Dialect

  flyway:
    enabled: true
    user: root
    password: pass

metrics:
  testGroupId: ${TEST_GROUP_ID}
  provider: ${PROVIDER}

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metric